{% set name = "click-repl" %}
{% set version = "0.4.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
    sha256: 52f8962ff0fdae8105d568123b144951257b6bfcfb44ff6f043379c307d0a8ac
  - url: https://github.com/click-contrib/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
    sha256: 2459c846a46476789a0087a4a77606881e5b4dd18f63b91aa896a3799bd1342c
    folder: gh

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - click >=7.0,<9.0
    - prompt_toolkit >=3.0.36
    - typing_extensions >=4.7.0

test:
  source_files:
    - gh/tests
  imports:
    - click_repl
  requires:
    - pip
    - pytest >=7.2.1
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest gh/tests

about:
  home: https://github.com/click-contrib/click-repl
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: REPL plugin for Click
  description: |
    click-repl turns a click-based application into a REPL, enabling
    multiple commands to be executed in single session, with a single
    shared context. Supports tab completion and command history.
  dev_url: https://github.com/click-contrib/click-repl
  doc_url: https://github.com/click-contrib/click-repl/blob/master/README.md

extra:
  recipe-maintainers:
    - mcg1969
