{% set name = "click-repl" %}
{% set version = "0.4.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
    sha256: c32a1cf6f95e5bd6e92076f81ce24eafd33f2f0ffb0135887e335b8e446d1c0b
  - url: https://github.com/click-contrib/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
    sha256: b393a134da532580e1fb9e43a035a935f7185d1372ddef4d435b42e25d1aebc5
    folder: gh

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - click >=7.0,<9.0
    - prompt_toolkit >=3.0.36
    - typing_extensions >=4.7.0

test:
  source_files:
    - gh/tests
  imports:
    - click_repl
  requires:
    - pip
    - pytest >=7.2.1
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest gh/tests

about:
  home: https://github.com/click-contrib/click-repl
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: REPL plugin for Click
  description: |
    click-repl turns a click-based application into a REPL, enabling
    multiple commands to be executed in single session, with a single
    shared context. Supports tab completion and command history.
  dev_url: https://github.com/click-contrib/click-repl
  doc_url: https://github.com/click-contrib/click-repl/blob/master/README.md

extra:
  recipe-maintainers:
    - mcg1969
