travis:
  secure:
    BINSTAR_TOKEN: PlVws480YttSOPWaehGavk96UIQBgG0lwsytBlt6dyCZCQkB/QxRteOaXVyCaK/WvkVuuHJpBOV0KSWAQhQmpBBifpP1dbGU3+vRAFTuZMABowWx0MXXeMCj+68nV1bNVPfGdr9rvSNnHh/ud78hjI1WMW/DtGja4fVg2C2cauBuG/UnttgFhkckncd2owIkgWVfEudyH6W7gsskqj4bFCzSagMyNxyt3wYwThSs4L5ZlpfiBNY7xRkyVg0LaOrDDcuXPM7EIwB4VTqRyzVuoeLCCzTzV0b1smsltDzaLHWX1tTs0l3DAQ+dGlUHSWenMXN62yVNOS869BzNe0VP1Cpo7+Ccd94U4avVscVT2quDol42jtWhRZ3We+rVWfL5eEPxRSK7GfQNH+gbWaAjbDnEGoTkXp1bUeHXff/AubTwQh/mOzQt/vytjMmWMkW9OYvmHgGOJNC7XVMcs5skGL/e0xDU7W5YWop4OJwQhegulOPBZdtWEB8nlT81gGjP7WRlq37Q8qkaXkO0nAlHTKgVWw8il1bRK2UXOreJQtmjRBAjK/sGedyy0onrSRBpZaE1eUf6VgIlZbo7gHEUWCpWxSGXJUZCCb44jkFudFwXf0rS6FA5a3XVHwrWVIuWji9mZ9FYb9F5OYt9z3aB6nIoCTr5/ODtwONH0U0SpBA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
