travis:
  secure:
    BINSTAR_TOKEN: AvOWvN5f1LAA0hCNd4OSU5xyJCyJOuMiYudiz5buQN/c9j97Ldjw+SrrmVgwAqdfuncg7ffVI9tGle7ip7lcp266TDbjW4Gnnhax81YvIPWOD5z8v3sv/JF+rG/UwrCv9Bl0FYNlssx6AiR7n6+OCFB/wvq+Y5eBf2toP96B+eUkhE2hRSkfibtTIE5dG+W8pDTdXD3RaBsLYModoCNk+NA756HPTJn053lfYUNLS/cEO9lDPIsq/SUv1dDSdiW0dHzwXD/zOQvdiYg7Lnk6FKJuaUaqeIlUPQ3o2jmO4ZyTwYcZhP2l1Z3SatY4OVLLnpzfBH+tbANRUMWW4GX8wO1pS5lkRybP8xVJoVD4HlqCAgLtcizKSA2jIlmfV4gllSI5pcCRm3m2F3Jp23tzZUjtz6gfzAHk4TG95Lcm8SN/EiV7ud2tM/Kt40NveHD39eGboMPcfZN4gcCPf2B90MPw6GdHRefu68NYNJbXh2AJM/SItBtQJnyPyuFXdZVZNeO3KJGwwgjXCim62MRqSvo3SCWQzatfKjjPPfxcnjuiwv1P1KGVKP7QbqYMhM63VUhsxpmaxCiXVR9AJLhtbPnb3UpU6OfPFR/6QNSTTbodLgTulWYujP1b2TuKdBERlBPW4EZADonKECdd4V/cAl5nnxddqpyBI+44Sh1t/iA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
